In [2]:
import numpy as np

In [3]:
zero_vector = np.zeros(5)

In [4]:
zero_matrix = np.zeros((5,3))

In [6]:
zero_vector

array([0., 0., 0., 0., 0.])

In [7]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
empty_matrix = np.empty((5,5))

In [9]:
empty_matrix

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.20161933e-306, 7.56587585e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.33511018e-306, 6.23057689e-307],
       [1.86921279e-306, 8.90098127e-307, 1.78020848e-306,
        1.60219035e-306, 1.42418172e-306],
       [2.04712906e-306, 7.56589622e-307, 1.11258277e-307,
        8.90111708e-307, 3.91786943e-317]])

In [10]:
x = np.array([1,2,3])

In [11]:
y = np.array([2,4,6])

In [12]:
x

array([1, 2, 3])

In [13]:
y

array([2, 4, 6])

In [14]:
np.array([[1,3], [5,9]])

array([[1, 3],
       [5, 9]])

In [15]:
a = np.array([[1,3], [5,9]])

In [16]:
a.transpose()

array([[1, 5],
       [3, 9]])

In [17]:
x = numpy.array([[3,6],[5,7]])

NameError: name 'numpy' is not defined

In [18]:
x = np.array([[3,6],[5,7]])

In [19]:
x

array([[3, 6],
       [5, 7]])

In [2]:
import numpy as np

In [4]:
x = np.array([1,2,3])
y = np.array([2,4,6])
X = np.array([[1,2,3], [4,5,6]])
Y = np.array([[2,4,6], [8,10,12]])

In [5]:
x[2]

3

In [6]:
x[0:2]

array([1, 2])

In [7]:
z = x + y

In [8]:
z

array([3, 6, 9])

In [9]:
X[:,1]

array([2, 5])

In [10]:
Y[:,1]

array([ 4, 10])

In [11]:
Y

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
X[:,1] + Y[:,1]

array([ 6, 15])

In [13]:
X[1,:]

array([4, 5, 6])

In [14]:
X[1,:] + Y[1,:]

array([12, 15, 18])

In [19]:
X[1]

array([4, 5, 6])

In [20]:
np.array([2,4]) + np.array([6,8])

array([ 8, 12])

In [21]:
x = np.array([1,2,5])
x[1:2]

array([2])

In [23]:
a = np.array([1,2])
b = np.array([3,4,5])
a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [24]:
z1 = np.array([1,3,5,7,9])

In [25]:
z2 = z1 + 1

In [26]:
z1

array([1, 3, 5, 7, 9])

In [27]:
z2

array([ 2,  4,  6,  8, 10])

In [28]:
ind = [0,2,3]

In [29]:
z1[ind]

array([1, 5, 7])

In [30]:
ind = np.array([0,2,3])

In [31]:
z1[ind]

array([1, 5, 7])

In [32]:
z1 > 6

array([False, False, False,  True,  True])

In [33]:
z1[z1 > 6]

array([7, 9])

In [34]:
z2[z1 > 6]

array([ 8, 10])

In [35]:
ind = z1 > 6

In [36]:
ind

array([False, False, False,  True,  True])

In [37]:
z1[ind]

array([7, 9])

In [38]:
z2[ind]

array([ 8, 10])

In [39]:
z1 = np.array([1,3,5,7,9])

In [40]:
w = z1[0:3]

In [41]:
w

array([1, 3, 5])

In [42]:
w[0] = 3

In [43]:
w

array([3, 3, 5])

In [44]:
z1

array([3, 3, 5, 7, 9])

In [45]:
z1 = np.array([1,3,5,7,9])

In [46]:
ind = np.array([0,1,2])

In [47]:
z1
ind

array([0, 1, 2])

In [48]:
w = z1[ind]

In [49]:
w

array([1, 3, 5])

In [50]:
w[0] = 3

In [51]:
w

array([3, 3, 5])

In [52]:
z1

array([1, 3, 5, 7, 9])

In [53]:
c = b[1:]
b[a] is c


False

In [54]:
np.linspace(0,100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [55]:
np.logspace(1,2,10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [56]:
np.logspace(np.log10(250),np.log10(500),10)

array([250.        , 270.01493472, 291.63225989, 314.98026247,
       340.19750004, 367.43362307, 396.85026299, 428.62199143,
       462.93735614, 500.        ])

In [57]:
np.shape()

TypeError: _shape_dispatcher() missing 1 required positional argument: 'a'

In [58]:
X = np.array([[1,2,3],[4,5,6]])

In [59]:
X.shape

(2, 3)

In [60]:
x.size

3

In [61]:
X.size

6

In [62]:
np.random.random(10)

array([0.33124791, 0.3387536 , 0.66487168, 0.68995936, 0.03639151,
       0.48512835, 0.97851796, 0.48822715, 0.45783879, 0.23080093])

In [63]:
x = _

In [64]:
x

array([0.33124791, 0.3387536 , 0.66487168, 0.68995936, 0.03639151,
       0.48512835, 0.97851796, 0.48822715, 0.45783879, 0.23080093])

In [65]:
np.any(x> 0.9)

True

In [66]:
np.all(x >= 0.1)

False

In [6]:
z = np.zeros((5,3))

In [8]:
z[(0,1)] = 1

In [9]:
z

array([[0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])